### ISSUE TITLE
security

### ISSUE THREAD

**Issue by dominictarr** [xat/airtar#1]
tar has a (seemingly) weird thing where it can also contain absolute paths, so it would be easy to send someone a tarfile innocently wrote files to a subdirectory, BUT ALSO maliciously overwrote your .bashrc file... which could be used to cause all sorts of mayhem!

Since you are already using node.js I'd recommend using @mafintosh's [tar-fs](https://github.com/mafintosh/tar-fs) and filtering out non-relative paths (or warning the user, etc)

There could certainly be a module that gave you safe-untar but I don't know of it offhand.

**Comment by xat** [comment]
Thanks for the advice, I wasn't aware of that. Absolute paths are now disallowed.

Yep, I'm already looking into tar-fs. Totally agree that a JS-only solution would be cooler.

**Comment by dominictarr** [comment]
cool - although, you fixed it by filtering on the sender's side, which is not as secure as filtering it on the receiver side. I could still send you a file with the old version of your code, and the victim, using the latest receiver code would still be vulnerable.

**Comment by dominictarr** [comment]
some useful info here: http://www.linfo.org/tarbomb.html

**Comment by xat** [comment]
Using tar-fs and also checking for absolute paths on the receiver side now.

Maybe some sort of `--overwrite` parameter would be nice. Only if that parameter is set files would get overwritten. mkdirp already seems to throw an error when trying to create an directory on a path which contains a file in it.

**Comment by mafintosh** [comment]
tar-fs actually already rewrites all absolute paths to relative ones for this reason. so `/usr/local/lib` gets extracted in `./usr/local/lib` (https://github.com/mafintosh/tar-fs/blob/master/index.js#L205)

**Comment by xat** [comment]
ah nice :)

**Comment by xat** [comment]
So, to summerize it:
- the sender has an absolute-path check
- on the receiver-side files get extracted relatively, even if they where absolute paths before (thanks to `tar-fs`)
- files will only get overwritten when explicity using the `--overwrite` parameter
- a user must explicity specify a target when calling `airuntar`
- there is a small security notice in the readme which states that `airtar` should only be used in a trusted network

@dominictarr do you have any further concerns?

**Comment by dominictarr** [comment]
@xat I am satisfied.

**Comment by xat** [comment]
great :)
thanks for your input.
